---
name: Apache-Session-Wrapper
version: 0.26
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: A simple wrapper around Apache::Session
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Apache::Session: 1.6
  Class::Container: 0
  Exception::Class: 0
  Params::Validate: 0.7
build_requires:
  Apache::Test: 0
provides:
  Apache::Session::Wrapper:
    file: lib/Apache/Session/Wrapper.pm
    version: 0.26
generated_by: Module::Build version 0.2702
